
services:
  app:
    image: pylonai:0.0.1
    build:
      context: .
      dockerfile: Dockerfile
    container_name: PylonEmployeeApp
    ports:
      - 3000:5000
    env_file:
      - .env
    depends_on:
      - db
  
  db:
    image: postgres:16.1
    container_name: PylonEmployeeDB
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=${DOCKERDBNAME}
      - POSTGRES_USER=${DOCKERDBUSER}
      - POSTGRES_PASSWORD=${DOCKERDBPASS}
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: